- hosts: all
  roles:
    - add-build-sshkey
    - prepare-workspace
    # This role ensures basic connectivity and produces some
    # helpful information in zuul-info/
    - validate-host
    # This role ensures standard output directories are created
    # on each remote node
    - ensure-output-dirs
    # This roles copies the ansible inventory to zuul-info/
    # for debugging purposes
    - log-inventory
